name: fe_lab_clinicas_adm
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.9

  flutter_getit: ^3.0.1
  fe_lab_clinicas_core:
    path: ../fe_lab_clinicas_core
  asyncstate: ^2.1.1-dev.1
  shared_preferences: ^2.5.5
  validatorless: ^1.2.5
  dio: ^5.9.2
  signals_flutter: ^6.3.0
  json_annotation: ^4.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  json_serializable: ^6.14.0
  build_runner: ^2.15.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
  
  
  

  
  

  
  
  
  
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/font/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/font/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/font/Montserrat-Light.ttf
          weight: 300
        - asset: assets/font/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/font/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/font/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/font/Montserrat-Black.ttf
          weight: 900
        - asset: assets/font/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
  
  
  
